context:
  version: "0.14.8"

package:
  name: bottom
  version: ${{ version }}

source:
  url: https://github.com/ClementTsang/bottom/archive/${{ version }}.tar.gz
  sha256: be10adada9ec1e5dd741dcb5581c4e0ebd45cb5bdae213dd296b29511363a770

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - btm --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Yet another cross-platform graphical process/system monitor
  homepage: https://clementtsang.github.io/bottom
  repository: https://github.com/ClementTsang/bottom

extra:
  recipe-maintainers:
    - danielnachun
